#' Add \code{model*.RDS} to .gitignore
#'
#' Adds file types generated by
#' \code{board} of type \code{model*.RDS} to .gitignore. Model types
#' can be very large, so you may not want to save them to a git repo.
#'
#' @export
git_ignore_models <- function() {
  usethis::use_git_ignore("model*.RDS")
}
